---
title: "Proyectos"
layout: "proyectos/list"
---

- title: Estudio de Valores Perdidos en R
  cluster: "R"
  content: >
  Estudio de la Recuperación de un Análisis Factorial Confirmatorio sobre una matriz de varianzas y covarianzas cuyos datos presentaban valores perdidos.
  image: /rstudio.png
  #featured:
  #name: Demo
  #link: https://hugo-profile.netlify.app
  badges:
  - "R"
  - "mice"
  - "mcar"
  - "missing  data"
  - "AFC"
  links:
  - icon: fab fa-github fa-2x
      url: https://github.com/aliciagilmatute/Estudio-Valores-Perdidos
    #- icon: fab fa-twitter
    #  url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

- title: Simulación Estadística
  cluster: "R"
  content: >
  Una serie de proyectos de simulación relacionados con la estadística.
  image: /rstudio.png
  #featured:
  #name: Demo
  #link: https://django-converter.herokuapp.com
  badges:
  - "R"
  - "simulación"
  - "Bootstrap"
  - "estadística"
  links:
  - icon: fab fa-github fa-2x
  url: https://github.com/aliciagilmatute/Simulacion

- title: Machine Learning (Supervised)
  cluster: "Python"
  content: >
  Una serie de proyectos de clasificación con técnicas de Machine Learning Supervised

  image: /Python.png
  #featured:
  #name: Demo
  #link: https://django-converter.herokuapp.com
  badges:
  - "Python"
  - "Machine Learning"
  - "KNN"
  - "MVS"
  - "Random Forest"
  - "sklearn"
  - "pandas"
  - "numpy"
  links:
  - icon: fab fa-github fa-2x
  url: https://github.com/aliciagilmatute/Machine-Learning-supervised-

- title: Machine Learning (Unsupervised)
  cluster: "Python"
  content: >
  Una serie de proyectos de clustering y reducción de dimensionalidad.

  image: /Python.png
  #featured:
  #name: Demo
  #link: https://django-converter.herokuapp.com
  badges:
  - "Python"
  - "Machine Learning"
  - "DBSCAN"
  - "PCA"
  - "GMM"
  - "clustering"
  - "sklearn"
  - "pandas"
  - "numpy"
  links:
  - icon: fab fa-github fa-2x
  url: https://github.com/aliciagilmatute/Machine-Learning--unsupervised-

- title: Análisis Multinivel Bayesiano
  cluster: "R"
  content: >
  Este estudio explora el análisis multinivel desde un enfoque bayesiano para evaluar la variabilidad del rendimiento en matemáticas entre 10 centros educativos

  image: /rstudio.png
  #featured:
  #name: Demo
  #link: https://django-converter.herokuapp.com
  badges:
  - "RStudio"
  - "Multilevel Models"
  - "Bayesian"
  - "Statistics"
  - "Stan"
  - "Hierarchical Models"
  - "Data Analysis"
  links:
  - icon: fab fa-github fa-2x
  url: https://github.com/aliciagilmatute/Analisis-Multinivel-Bayesiano

- title: Algoritmo Genético
  cluster: "Python"
  content: >
  Algoritmo Genético que pretende resolver el problema del viajante (TSP) desde dos lógicas diferentes.

  image: /Python.png
  #featured:
  #name: Demo
  #link: https://django-converter.herokuapp.com
  badges:
  - "Python"
  - "Genetic Algorithm"
  - "Genetic Analysis"
  - "Linear Regression"
  - "Linear Models"
  - "Genetic Optimitation Algorithm"
  - "sklearn"
  - "pandas"
  - "numpy"
  links:
  - icon: fab fa-github fa-2x
  url: https://github.com/aliciagilmatute/Algoritmo-Genetico



    #- title: Hugo Profile V2
    # content: A clean and simple Hugo template for personal portfolio and blog.
    # image: /images/projects/profile2.jpg
    #featured:
    # name: Demo V2
    #link: https://hugo-profile-2.netlify.app
    #badges:
    # - "Hugo"
    # - "Bootstrap"
    #- "Javascript"
    #links:
    # - icon: fab fa-github
    #  url: https://github.com/gurusabarish/HugoProfileV2

